In [3]:
# PyTorch Fundamentals: Tensors
#
!nvidia-smi
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


Tue Oct 21 01:29:33 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.15                 Driver Version: 581.15         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   39C    P8              7W /   95W |    1377MiB /   8188MiB |      8%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [18]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # Datatype
                               device=None, # What device is tenosr on
                               requires_grad=False)

In [11]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [7]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [8]:
float_32_tensor / float_16_tensor

tensor([1., 1., 1.])

In [25]:
float_32_tensor = torch.arange(start=0, end=21, step=2)
float_32_tensor

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [28]:
float_32_tensor += torch.tensor([1]*11)
float_32_tensor

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])