In [1]:
%pip install torch
%pip install pandas
%pip install numpy
%pip install matplotlib

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


PyTorch Fundamentals!
---
https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
# PyTorch Fundamentals: Tensors
#
!nvidia-smi
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


Tue Oct 21 01:06:33 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.15                 Driver Version: 581.15         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   48C    P5              9W /   70W |    1289MiB /   8188MiB |     19%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Introduction to Tensors

### Creating Tensors

There are many different kinds of Tensors
- Scalar -> A single number
- Vector -> A number with direction
- Matrix -> A 2D array of numbers
- Tensor => An n-dimensional array of numbers

![image.png](..\images\tensor.png)

https://pytorch.org/docs/stable/tensors.html

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim


0

In [5]:
scalar.item()

7

In [6]:
# Vector
# Vector has magnitude and direction
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

Anytime we code data into numbers its of a tensor data-type

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

Takes in the elements of a list and the list

In [14]:
# Tensor

TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

Most of Tensors creation will be done by PyTorch rather than us manually creating Tensors but we will need to understand it still

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

![image.png](../images/image5.png)

If we were to add another matrix to our tensor it would have 2 matrices inside it and the shape would be (2, 3, 3)

How would we then reshape and manipulate our data within the Tensor?

In [18]:
TENSOR[0 :] += torch.tensor([1, 1, 1])
TENSOR

tensor([[[ 2,  3,  4],
         [ 5,  6,  7],
         [ 8,  9, 10]]])

This only manipulates our 0th dimension of data, how would we append data at the start?

In [45]:
TENSOR = torch.cat((TENSOR, torch.tensor([[[10, 11, 12]]])), dim=1)
TENSOR

tensor([[[10, -1,  0],
         [ 2,  3,  4],
         [ 5,  6,  7],
         [ 8,  9, 10],
         [10, 11, 12],
         [10, 11, 12]]])

We appended our data but we want to append it from the start rather than the end we would need follow the rules of torch.cat
When using torch.cat((tensor_A, tensor_B), dim=N), All dimension of tensor_A and tensor_B must match, except for the dimesion specified bt dim=N


Since we want to concatenate along the 0th dimension, the sizes of dim=1 and dim=2 must be identical for both tensors.

To solve this we must change the structure of the data we are passing through to torch.tensor()

In [20]:
new_row_at_start = torch.tensor([[[10, -1, 0]]])
TENSOR = torch.cat((new_row_at_start, TENSOR), dim=1)
TENSOR

tensor([[[10, -1,  0],
         [ 2,  3,  4],
         [ 5,  6,  7],
         [ 8,  9, 10],
         [10, 11, 12]]])

## Random Tensors
### Why Random Tensors?
- In machine learning, we often want to initialize our model with random weights.
- Random tensors are important because we the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random rumbers to better represent the data

`Start with random numbers -> Look at data -> Update random numbers -> Look at data -> Update random numbers`

In [21]:
# Create random tensor of size/shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9956, 0.7830, 0.4908, 0.3894],
        [0.2503, 0.5304, 0.1332, 0.0431],
        [0.6604, 0.9681, 0.4729, 0.0335]])

In [22]:
random_tensor.shape

torch.Size([3, 4])

In [23]:
random_tensor.ndim

2

In [24]:
# Creating a random tensor with similar shape to an image tensor
image_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (RGB)
image_tensor.shape, image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [25]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
zeros.shape, zeros.ndim, zeros.dtype

(torch.Size([3, 4]), 2, torch.float32)

In [27]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Creating a range of tensors and tensors-like

In [29]:
#Using torch.arange()
torch.arange(0, 10, step=2)

tensor([0, 2, 4, 6, 8])

In [30]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
output_tensor = torch.empty(11)
output_tensor

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
torch.arange(0, 11, out=output_tensor)
output_tensor

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
# using torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor DataTypes

**Note:** Tensor datatypes os one of the big 3 errors
1. Tensors not right data type
2. Tensor not the right shape
3. Tensors not on the right device

https://en.wikipedia.org/wiki/Precision_(computer_science)

In [ ]:
# Float 32 tensor
# Precision in Computing

### https://docs.pytorch.org/docs/stable/tensors.html

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # Datatype
                               device=None, # What device is tenosr on
                               requires_grad=False) # Whether or not to track gradients with this Tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [41]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

tensor([3., 6., 9.], dtype=torch.float16)